export default {
  gameContextData: {
    context: "availableMissions",
    repairOptions: [
      {
        type: "noRepair",
        notEnoughDisplay: "Repaired vehicle needed",
        available: false,
        label: "No",
      },
      {
        notEnoughDisplay: "Not enough vouchers for repair",
        type: "voucherRepair",
        label: "For 1 voucher",
        cost: 1,
        available: false,
      },
      {
        notEnoughDisplay: "Not enough money for repair",
        type: "moneyRepair",
        label: "For 1000 money",
        cost: 1000,
        available: true,
      },
    ],
    isWalking: false,
    isCareerActive: true,
    missions: [
      {
        progress: {
          default: {
            attempts: [
              {
                data: {},
                unlockedStars: {},
                date: 1705633997,
                type: "none",
                attemptNumber: 1,
                humanDate: "2024-01-19T03:13:17Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705633997,
                type: "none",
                attemptNumber: 2,
                humanDate: "2024-01-19T03:13:17Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705633997,
                type: "none",
                attemptNumber: 3,
                humanDate: "2024-01-19T03:13:17Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705633997,
                type: "none",
                attemptNumber: 4,
                humanDate: "2024-01-19T03:13:17Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705633997,
                type: "none",
                attemptNumber: 5,
                humanDate: "2024-01-19T03:13:17Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705633997,
                type: "none",
                attemptNumber: 6,
                humanDate: "2024-01-19T03:13:17Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705633997,
                type: "none",
                attemptNumber: 7,
                humanDate: "2024-01-19T03:13:17Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705633997,
                type: "none",
                attemptNumber: 8,
                humanDate: "2024-01-19T03:13:17Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705633997,
                type: "none",
                attemptNumber: 9,
                humanDate: "2024-01-19T03:13:17Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705633997,
                type: "none",
                attemptNumber: 10,
                humanDate: "2024-01-19T03:13:17Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705633997,
                type: "none",
                attemptNumber: 11,
                humanDate: "2024-01-19T03:13:17Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705633997,
                type: "none",
                attemptNumber: 12,
                humanDate: "2024-01-19T03:13:17Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705633997,
                type: "none",
                attemptNumber: 13,
                humanDate: "2024-01-19T03:13:17Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705633997,
                type: "none",
                attemptNumber: 14,
                humanDate: "2024-01-19T03:13:17Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705633997,
                type: "none",
                attemptNumber: 15,
                humanDate: "2024-01-19T03:13:17Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705633997,
                type: "none",
                attemptNumber: 16,
                humanDate: "2024-01-19T03:13:17Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705633997,
                type: "none",
                attemptNumber: 17,
                humanDate: "2024-01-19T03:13:17Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705633997,
                type: "none",
                attemptNumber: 18,
                humanDate: "2024-01-19T03:13:17Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705633997,
                type: "none",
                attemptNumber: 19,
                humanDate: "2024-01-19T03:13:17Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705633997,
                type: "none",
                attemptNumber: 20,
                humanDate: "2024-01-19T03:13:17Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705633997,
                type: "none",
                attemptNumber: 21,
                humanDate: "2024-01-19T03:13:17Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705633997,
                type: "none",
                attemptNumber: 22,
                humanDate: "2024-01-19T03:13:17Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705633997,
                type: "none",
                attemptNumber: 23,
                humanDate: "2024-01-19T03:13:17Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705633997,
                type: "none",
                attemptNumber: 24,
                humanDate: "2024-01-19T03:13:17Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705633997,
                type: "none",
                attemptNumber: 25,
                humanDate: "2024-01-19T03:13:17Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705634038,
                type: "none",
                attemptNumber: 26,
                humanDate: "2024-01-19T03:13:58Z",
              },
            ],
            aggregate: {
              bestType: "none",
              mosttimespan: 1705634038,
              attemptCount: 26,
              passed: false,
              completed: false,
            },
            leaderboards: { recent: [26, 25, 24, 23, 22] },
          },
        },
        hasUserSettings: true,
        name: "missions.chase.wcusa.unpaidFines.title",
        userSettings: [
          {
            values: [{ v: 1, l: "Gavril Grand Marshal " }],
            value: 1,
            type: "select",
            key: "setupModuleVehicles",
            label: "ui.busRoute.vehicle",
          },
          {
            values: [
              { v: false, l: "ui.common.no" },
              { v: true, l: "ui.common.yes" },
            ],
            value: true,
            type: "select",
            key: "setupModuleTraffic",
            label: "missions.missions.general.userSettings.trafficEnabled",
          },
        ],
        preview: ["images/noimage.png", "images/noimage.png"],
        description:
          "Stop the driver who is unwilling to pay fines!Stop the driver who is unwilling to pay fines!Stop the driver who is unwilling to pay fines!Stop the driver who is unwilling to pay fines!Stop the driver who is unwilling to pay fines!Stop the driver who is unwilling to pay fines!Stop the driver who is unwilling to pay fines!Stop the driver who is unwilling to pay fines!Stop the driver who is unwilling to pay fines!Stop the driver who is unwilling to pay fines!Stop the driver who is unwilling to pay fines!Stop the driver who is unwilling to pay fines!Stop the driver who is unwilling to pay fines!Stop the driver who is unwilling to pay fines!Stop the driver who is unwilling to pay fines!Stop the driver who is unwilling to pay fines!Stop the driver who is unwilling to pay fines!Stop the driver who is unwilling to pay fines!Stop the driver who is unwilling to pay fines!Stop the driver who is unwilling to pay fines!Stop the driver who is unwilling to pay fines!Stop the driver who is unwilling to pay fines!Stop the driver who is unwilling to pay fines!",
        id: "west_coast_usa/chase/001-unpaid",
        currentProgressKey: "default",
        formattedProgress: {
          formattedProgressByKey: {
            default: {
              attempts: {
                rows: {},
                labels: ["#", "", "", "bigMap.progressLabels.time"],
              },
              ownAggregate: {
                rows: [[{ text: "26" }, { text: "-" }]],
                newBestKeys: ["none", "newBestTime"],
                labels: ["Attempts", "bigMap.progressLabels.bestTime"],
              },
            },
          },
          progressKeyTranslations: {
            default: "missions.progressKeyLabels.default",
          },
          defaultProgressKey: "default",
          allProgressKeys: ["default"],
          unlockedStars: {
            stars: [
              {
                rewards: [
                  {
                    rewardAmount: 450,
                    icon: "star",
                    attributeKey: "money",
                  },
                  { rewardAmount: 5, icon: "star", attributeKey: "beamXP" },
                  {
                    rewardAmount: 50,
                    icon: "star",
                    attributeKey: "specialized",
                  },
                ],
                defaultStarIndex: 1,
                unlocked: false,
                isDefaultStar: true,
                key: "complete",
                label: {
                  txt: "missions.missions.stars.justFinish",
                  context: {
                    hideoutScl: "10",
                    timeFailText: "missions.chase.general.timeFail",
                    hideoutFailText: "missions.chase.general.hideoutFail",
                    timeBronze: "180",
                    maxTimeWindow: "60",
                    suspectModel: "midsize",
                    suspectConfigPath: "vehicles/midsize/DX_A.pc",
                    distanceLimit: "250",
                    timeLimit: "120",
                    minTimeWindow: "50",
                    aiAggression: "0.6000000238",
                    suspectConfig: "DX_A",
                    distanceFailText: "missions.chase.general.distanceFail",
                    damageFailText: "missions.chase.general.damageFail",
                    distanceWarnText: "missions.chase.general.distanceWarn",
                    damageLimit: "20000",
                    timeGold: "30",
                    fleeTriggerScl: "10",
                    timeSilver: "60",
                    fleeDelay: "90",
                    startTitle: "missions.chase.wcusa.unpaidFines.title",
                    startText: "missions.chase.wcusa.unpaidFines.start",
                  },
                },
              },
              {
                rewards: [
                  {
                    rewardAmount: 450,
                    icon: "star",
                    attributeKey: "money",
                  },
                  { rewardAmount: 5, icon: "star", attributeKey: "beamXP" },
                  {
                    rewardAmount: 50,
                    icon: "star",
                    attributeKey: "specialized",
                  },
                ],
                defaultStarIndex: 2,
                unlocked: false,
                isDefaultStar: true,
                key: "timeSilver",
                label: {
                  txt: "missions.chase.stars.silver",
                  context: {
                    hideoutScl: "10",
                    timeFailText: "missions.chase.general.timeFail",
                    hideoutFailText: "missions.chase.general.hideoutFail",
                    timeBronze: "180",
                    maxTimeWindow: "60",
                    suspectModel: "midsize",
                    suspectConfigPath: "vehicles/midsize/DX_A.pc",
                    distanceLimit: "250",
                    timeLimit: "120",
                    minTimeWindow: "50",
                    aiAggression: "0.6000000238",
                    suspectConfig: "DX_A",
                    distanceFailText: "missions.chase.general.distanceFail",
                    damageFailText: "missions.chase.general.damageFail",
                    distanceWarnText: "missions.chase.general.distanceWarn",
                    damageLimit: "20000",
                    timeGold: "30",
                    fleeTriggerScl: "10",
                    timeSilver: "60",
                    fleeDelay: "90",
                    startTitle: "missions.chase.wcusa.unpaidFines.title",
                    startText: "missions.chase.wcusa.unpaidFines.start",
                  },
                },
              },
              {
                rewards: [
                  {
                    rewardAmount: 450,
                    icon: "star",
                    attributeKey: "money",
                  },
                  { rewardAmount: 5, icon: "star", attributeKey: "beamXP" },
                  {
                    rewardAmount: 50,
                    icon: "star",
                    attributeKey: "specialized",
                  },
                ],
                defaultStarIndex: 3,
                unlocked: false,
                isDefaultStar: true,
                key: "timeGold",
                label: {
                  txt: "missions.chase.stars.gold",
                  context: {
                    hideoutScl: "10",
                    timeFailText: "missions.chase.general.timeFail",
                    hideoutFailText: "missions.chase.general.hideoutFail",
                    timeBronze: "180",
                    maxTimeWindow: "60",
                    suspectModel: "midsize",
                    suspectConfigPath: "vehicles/midsize/DX_A.pc",
                    distanceLimit: "250",
                    timeLimit: "120",
                    minTimeWindow: "50",
                    aiAggression: "0.6000000238",
                    suspectConfig: "DX_A",
                    distanceFailText: "missions.chase.general.distanceFail",
                    damageFailText: "missions.chase.general.damageFail",
                    distanceWarnText: "missions.chase.general.distanceWarn",
                    damageLimit: "20000",
                    timeGold: "30",
                    fleeTriggerScl: "10",
                    timeSilver: "60",
                    fleeDelay: "90",
                    startTitle: "missions.chase.wcusa.unpaidFines.title",
                    startText: "missions.chase.wcusa.unpaidFines.start",
                  },
                },
              },
              {
                rewards: [
                  {
                    rewardAmount: 1,
                    icon: "star",
                    attributeKey: "vouchers",
                  },
                ],
                defaultStarIndex: false,
                unlocked: false,
                isDefaultStar: false,
                key: "lowDamage",
                label: {
                  txt: "missions.chase.stars.lowDamage",
                  context: {
                    hideoutScl: "10",
                    timeFailText: "missions.chase.general.timeFail",
                    hideoutFailText: "missions.chase.general.hideoutFail",
                    timeBronze: "180",
                    maxTimeWindow: "60",
                    suspectModel: "midsize",
                    suspectConfigPath: "vehicles/midsize/DX_A.pc",
                    distanceLimit: "250",
                    timeLimit: "120",
                    minTimeWindow: "50",
                    aiAggression: "0.6000000238",
                    suspectConfig: "DX_A",
                    distanceFailText: "missions.chase.general.distanceFail",
                    damageFailText: "missions.chase.general.damageFail",
                    distanceWarnText: "missions.chase.general.distanceWarn",
                    damageLimit: "20000",
                    timeGold: "30",
                    fleeTriggerScl: "10",
                    timeSilver: "60",
                    fleeDelay: "90",
                    startTitle: "missions.chase.wcusa.unpaidFines.title",
                    startText: "missions.chase.wcusa.unpaidFines.start",
                  },
                },
              },
              {
                rewards: [
                  {
                    rewardAmount: 1,
                    icon: "star",
                    attributeKey: "vouchers",
                  },
                ],
                defaultStarIndex: false,
                unlocked: false,
                isDefaultStar: false,
                key: "perfectArrest",
                label: {
                  txt: "missions.chase.stars.perfectArrest",
                  context: {
                    hideoutScl: "10",
                    timeFailText: "missions.chase.general.timeFail",
                    hideoutFailText: "missions.chase.general.hideoutFail",
                    timeBronze: "180",
                    maxTimeWindow: "60",
                    suspectModel: "midsize",
                    suspectConfigPath: "vehicles/midsize/DX_A.pc",
                    distanceLimit: "250",
                    timeLimit: "120",
                    minTimeWindow: "50",
                    aiAggression: "0.6000000238",
                    suspectConfig: "DX_A",
                    distanceFailText: "missions.chase.general.distanceFail",
                    damageFailText: "missions.chase.general.damageFail",
                    distanceWarnText: "missions.chase.general.distanceWarn",
                    damageLimit: "20000",
                    timeGold: "30",
                    fleeTriggerScl: "10",
                    timeSilver: "60",
                    fleeDelay: "90",
                    startTitle: "missions.chase.wcusa.unpaidFines.title",
                    startText: "missions.chase.wcusa.unpaidFines.start",
                  },
                },
              },
            ],
            defaultUnlockedStarCount: 0,
            totalStars: 5,
            totalUnlockedStarCount: 0,
          },
        },
        defaultUserSettings: {
          setupModuleTraffic: true,
          setupModuleVehicles: 1,
        },
        hasUserSettingsUnlocked: true,
        leaderboardKey: "highscore",
        devMission: false,
        unlocks: {
          startable: true,
          backward: {},
          depth: 10,
          forward: ["west_coast_usa/chase/002-tamper", "west_coast_usa/chase/004-racer"],
          startableDetails: {
            met: true,
            condition: {
              level: 1,
              branchId: "specialized",
              type: "branchLevel",
            },
            label: {
              txt: "missions.missions.unlock.attributeLevel.atLeast",
              context: { level: 1, branchName: "ui.career.specialized" },
            },
          },
          maxBranchlevel: 1,
          branchTags: { specialized: true },
          visible: true,
        },
        missionTypeLabel: "bigMap.missionLabels.chase",
        additionalAttributes: [
          {
            icon: "directions_car",
            valueKey: "Own or Provided Vehicle",
            labelKey: "Vehicle Used",
          },
          { icon: "flag", valueKey: "Low", labelKey: "Difficulty" },
        ],
      },
      {
        progress: {
          default: {
            attempts: [
              {
                data: {},
                unlockedStars: {},
                date: 1705634089,
                type: "none",
                attemptNumber: 1,
                humanDate: "2024-01-19T03:14:49Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705634089,
                type: "none",
                attemptNumber: 2,
                humanDate: "2024-01-19T03:14:49Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705634089,
                type: "none",
                attemptNumber: 3,
                humanDate: "2024-01-19T03:14:49Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705634089,
                type: "none",
                attemptNumber: 4,
                humanDate: "2024-01-19T03:14:49Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705634089,
                type: "none",
                attemptNumber: 5,
                humanDate: "2024-01-19T03:14:49Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705634089,
                type: "none",
                attemptNumber: 6,
                humanDate: "2024-01-19T03:14:49Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705634089,
                type: "none",
                attemptNumber: 7,
                humanDate: "2024-01-19T03:14:49Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705634089,
                type: "none",
                attemptNumber: 8,
                humanDate: "2024-01-19T03:14:49Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705634089,
                type: "none",
                attemptNumber: 9,
                humanDate: "2024-01-19T03:14:49Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705634089,
                type: "none",
                attemptNumber: 10,
                humanDate: "2024-01-19T03:14:49Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705634089,
                type: "none",
                attemptNumber: 11,
                humanDate: "2024-01-19T03:14:49Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705634089,
                type: "none",
                attemptNumber: 12,
                humanDate: "2024-01-19T03:14:49Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705634089,
                type: "none",
                attemptNumber: 13,
                humanDate: "2024-01-19T03:14:49Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705634089,
                type: "none",
                attemptNumber: 14,
                humanDate: "2024-01-19T03:14:49Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705634089,
                type: "none",
                attemptNumber: 15,
                humanDate: "2024-01-19T03:14:49Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705634089,
                type: "none",
                attemptNumber: 16,
                humanDate: "2024-01-19T03:14:49Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705634089,
                type: "none",
                attemptNumber: 17,
                humanDate: "2024-01-19T03:14:49Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705634089,
                type: "none",
                attemptNumber: 18,
                humanDate: "2024-01-19T03:14:49Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705634089,
                type: "none",
                attemptNumber: 19,
                humanDate: "2024-01-19T03:14:49Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705634089,
                type: "none",
                attemptNumber: 20,
                humanDate: "2024-01-19T03:14:49Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705634089,
                type: "none",
                attemptNumber: 21,
                humanDate: "2024-01-19T03:14:49Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705634089,
                type: "none",
                attemptNumber: 22,
                humanDate: "2024-01-19T03:14:49Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705634089,
                type: "none",
                attemptNumber: 23,
                humanDate: "2024-01-19T03:14:49Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705634089,
                type: "none",
                attemptNumber: 24,
                humanDate: "2024-01-19T03:14:49Z",
              },
              {
                data: {},
                unlockedStars: {},
                date: 1705634089,
                type: "none",
                attemptNumber: 25,
                humanDate: "2024-01-19T03:14:49Z",
              },
            ],
            aggregate: {
              bestType: "none",
              completed: false,
              attemptCount: 25,
              passed: false,
              mosttimespan: 1705634089,
            },
            leaderboards: { recent: [25, 24, 23, 22, 21] },
          },
        },
        hasUserSettings: true,
        name: "missions.evade.wcusa.hideAtHome.title",
        userSettings: [
          {
            values: [
              { v: 1, l: "Gavril D-Series " },
              { type: "player", v: 2, l: "Player Vehicle" },
            ],
            value: 1,
            type: "select",
            key: "setupModuleVehicles",
            label: "ui.busRoute.vehicle",
          },
          {
            values: [
              { v: false, l: "ui.common.no" },
              { v: true, l: "ui.common.yes" },
            ],
            value: false,
            type: "select",
            key: "setupModuleTraffic",
            label: "missions.missions.general.userSettings.trafficEnabled",
          },
          {
            type: "bool",
            value: true,
            key: "useGroundmarkers",
            label: "missions.missions.general.userSettings.navigationMarkers",
          },
        ],
        preview: ["images/noimage.png"],
        description: "missions.evade.wcusa.hideAtHome.description",
        id: "west_coast_usa/evade/001-Hide",
        currentProgressKey: "default",
        formattedProgress: {
          formattedProgressByKey: {
            default: {
              attempts: {
                rows: {},
                labels: ["#", "", "", "bigMap.progressLabels.time"],
              },
              ownAggregate: {
                rows: [[{ text: "25" }, { text: "-" }]],
                newBestKeys: ["none", "newBestTime"],
                labels: ["Attempts", "bigMap.progressLabels.bestTime"],
              },
            },
          },
          progressKeyTranslations: {
            default: "missions.progressKeyLabels.default",
          },
          defaultProgressKey: "default",
          allProgressKeys: ["default"],
          unlockedStars: {
            stars: [
              {
                rewards: [
                  {
                    rewardAmount: 450,
                    icon: "star",
                    attributeKey: "money",
                  },
                  { rewardAmount: 5, icon: "star", attributeKey: "beamXP" },
                  {
                    rewardAmount: 50,
                    icon: "star",
                    attributeKey: "specialized",
                  },
                ],
                defaultStarIndex: 1,
                unlocked: false,
                isDefaultStar: true,
                key: "complete",
                label: {
                  txt: "missions.missions.stars.justFinish",
                  context: {
                    hideoutScl: "7",
                    roadblockChance: "0.5",
                    respawnRateDown: "0.400000006",
                    hideoutFailText: "missions.evade.general.destinationPolice",
                    timeBronze: "200",
                    goalOffenses: "3",
                    damageLimit: "20000",
                    longTime: "200",
                    propConfig: "lights",
                    timeSilver: "120",
                    pursuitMode: "2",
                    startTitle: "missions.evade.wcusa.hideAtHome.title",
                    evadeLimit: "60",
                    propConfigPath: "/vehicles/sawhorse/lights.pc",
                    propModel: "sawhorse",
                    propAmount: "1",
                    startText: "missions.evade.wcusa.hideAtHome.start",
                    arrestFailText: "missions.evade.general.arrestFail",
                    damageFailText: "missions.evade.general.damageFail",
                    arrestLimit: "5",
                    goalScore: "3000",
                    dropOffText: "missions.evade.general.destinationEscape",
                    spawnAmount: "2",
                    hideoutEvadeRadius: "50",
                    timeGold: "80",
                    goalPoliceWrecks: "3",
                    respawnRate: "1.799999952",
                    goalRoadblocks: "3",
                    goalCollisions: "3",
                    policeHeadStart: "0",
                  },
                },
              },
              {
                rewards: [
                  {
                    rewardAmount: 450,
                    icon: "star",
                    attributeKey: "money",
                  },
                  { rewardAmount: 5, icon: "star", attributeKey: "beamXP" },
                  {
                    rewardAmount: 50,
                    icon: "star",
                    attributeKey: "specialized",
                  },
                ],
                defaultStarIndex: 2,
                unlocked: false,
                isDefaultStar: true,
                key: "timeSilver",
                label: {
                  txt: "missions.chase.stars.silver",
                  context: {
                    hideoutScl: "7",
                    roadblockChance: "0.5",
                    respawnRateDown: "0.400000006",
                    hideoutFailText: "missions.evade.general.destinationPolice",
                    timeBronze: "200",
                    goalOffenses: "3",
                    damageLimit: "20000",
                    longTime: "200",
                    propConfig: "lights",
                    timeSilver: "120",
                    pursuitMode: "2",
                    startTitle: "missions.evade.wcusa.hideAtHome.title",
                    evadeLimit: "60",
                    propConfigPath: "/vehicles/sawhorse/lights.pc",
                    propModel: "sawhorse",
                    propAmount: "1",
                    startText: "missions.evade.wcusa.hideAtHome.start",
                    arrestFailText: "missions.evade.general.arrestFail",
                    damageFailText: "missions.evade.general.damageFail",
                    arrestLimit: "5",
                    goalScore: "3000",
                    dropOffText: "missions.evade.general.destinationEscape",
                    spawnAmount: "2",
                    hideoutEvadeRadius: "50",
                    timeGold: "80",
                    goalPoliceWrecks: "3",
                    respawnRate: "1.799999952",
                    goalRoadblocks: "3",
                    goalCollisions: "3",
                    policeHeadStart: "0",
                  },
                },
              },
              {
                rewards: [
                  {
                    rewardAmount: 450,
                    icon: "star",
                    attributeKey: "money",
                  },
                  { rewardAmount: 5, icon: "star", attributeKey: "beamXP" },
                  {
                    rewardAmount: 50,
                    icon: "star",
                    attributeKey: "specialized",
                  },
                ],
                defaultStarIndex: 3,
                unlocked: false,
                isDefaultStar: true,
                key: "timeGold",
                label: {
                  txt: "missions.chase.stars.gold",
                  context: {
                    hideoutScl: "7",
                    roadblockChance: "0.5",
                    respawnRateDown: "0.400000006",
                    hideoutFailText: "missions.evade.general.destinationPolice",
                    timeBronze: "200",
                    goalOffenses: "3",
                    damageLimit: "20000",
                    longTime: "200",
                    propConfig: "lights",
                    timeSilver: "120",
                    pursuitMode: "2",
                    startTitle: "missions.evade.wcusa.hideAtHome.title",
                    evadeLimit: "60",
                    propConfigPath: "/vehicles/sawhorse/lights.pc",
                    propModel: "sawhorse",
                    propAmount: "1",
                    startText: "missions.evade.wcusa.hideAtHome.start",
                    arrestFailText: "missions.evade.general.arrestFail",
                    damageFailText: "missions.evade.general.damageFail",
                    arrestLimit: "5",
                    goalScore: "3000",
                    dropOffText: "missions.evade.general.destinationEscape",
                    spawnAmount: "2",
                    hideoutEvadeRadius: "50",
                    timeGold: "80",
                    goalPoliceWrecks: "3",
                    respawnRate: "1.799999952",
                    goalRoadblocks: "3",
                    goalCollisions: "3",
                    policeHeadStart: "0",
                  },
                },
              },
              {
                rewards: [
                  {
                    rewardAmount: 1,
                    icon: "star",
                    attributeKey: "vouchers",
                  },
                ],
                defaultStarIndex: false,
                unlocked: false,
                isDefaultStar: false,
                key: "lowDamage",
                label: {
                  txt: "missions.evade.stars.lowDamage",
                  context: {
                    hideoutScl: "7",
                    roadblockChance: "0.5",
                    respawnRateDown: "0.400000006",
                    hideoutFailText: "missions.evade.general.destinationPolice",
                    timeBronze: "200",
                    goalOffenses: "3",
                    damageLimit: "20000",
                    longTime: "200",
                    propConfig: "lights",
                    timeSilver: "120",
                    pursuitMode: "2",
                    startTitle: "missions.evade.wcusa.hideAtHome.title",
                    evadeLimit: "60",
                    propConfigPath: "/vehicles/sawhorse/lights.pc",
                    propModel: "sawhorse",
                    propAmount: "1",
                    startText: "missions.evade.wcusa.hideAtHome.start",
                    arrestFailText: "missions.evade.general.arrestFail",
                    damageFailText: "missions.evade.general.damageFail",
                    arrestLimit: "5",
                    goalScore: "3000",
                    dropOffText: "missions.evade.general.destinationEscape",
                    spawnAmount: "2",
                    hideoutEvadeRadius: "50",
                    timeGold: "80",
                    goalPoliceWrecks: "3",
                    respawnRate: "1.799999952",
                    goalRoadblocks: "3",
                    goalCollisions: "3",
                    policeHeadStart: "0",
                  },
                },
              },
              {
                rewards: [
                  {
                    rewardAmount: 1,
                    icon: "star",
                    attributeKey: "vouchers",
                  },
                ],
                defaultStarIndex: false,
                unlocked: false,
                isDefaultStar: false,
                key: "perfectEscape",
                label: {
                  txt: "missions.evade.stars.perfectEscape",
                  context: {
                    hideoutScl: "7",
                    roadblockChance: "0.5",
                    respawnRateDown: "0.400000006",
                    hideoutFailText: "missions.evade.general.destinationPolice",
                    timeBronze: "200",
                    goalOffenses: "3",
                    damageLimit: "20000",
                    longTime: "200",
                    propConfig: "lights",
                    timeSilver: "120",
                    pursuitMode: "2",
                    startTitle: "missions.evade.wcusa.hideAtHome.title",
                    evadeLimit: "60",
                    propConfigPath: "/vehicles/sawhorse/lights.pc",
                    propModel: "sawhorse",
                    propAmount: "1",
                    startText: "missions.evade.wcusa.hideAtHome.start",
                    arrestFailText: "missions.evade.general.arrestFail",
                    damageFailText: "missions.evade.general.damageFail",
                    arrestLimit: "5",
                    goalScore: "3000",
                    dropOffText: "missions.evade.general.destinationEscape",
                    spawnAmount: "2",
                    hideoutEvadeRadius: "50",
                    timeGold: "80",
                    goalPoliceWrecks: "3",
                    respawnRate: "1.799999952",
                    goalRoadblocks: "3",
                    goalCollisions: "3",
                    policeHeadStart: "0",
                  },
                },
              },
            ],
            defaultUnlockedStarCount: 0,
            totalStars: 5,
            totalUnlockedStarCount: 0,
          },
        },
        defaultUserSettings: {
          setupModuleVehicles: 1,
          setupModuleTraffic: true,
          useGroundmarkers: true,
        },
        hasUserSettingsUnlocked: true,
        leaderboardKey: "highscore",
        devMission: false,
        unlocks: {
          startable: true,
          backward: {},
          depth: 10,
          forward: ["west_coast_usa/evade/002-Money"],
          startableDetails: {
            met: true,
            condition: {
              level: 1,
              branchId: "specialized",
              type: "branchLevel",
            },
            label: {
              txt: "missions.missions.unlock.attributeLevel.atLeast",
              context: { level: 1, branchName: "ui.career.specialized" },
            },
          },
          maxBranchlevel: 1,
          branchTags: { specialized: true },
          visible: true,
        },
        missionTypeLabel: "bigMap.missionLabels.evade",
        additionalAttributes: [{ icon: "flag", valueKey: "Low", labelKey: "Difficulty" }],
      },
    ],
    preselectedMissionId: "west_coast_usa/chase/001-unpaid",
  },
}
