export default {
  getMissionScreenData: {
    context: "availableMissions",
    isWalking: false,
    isCareerActive: false,
    missions: [
      {
        progress: {
          default: {
            attempts: [
              { data: { points: 94, medal: "silver" }, unlockedStars: {}, date: 1705633368, type: "none", attemptNumber: 1, humanDate: "2024-01-19T03:02:48Z" },
              { data: { points: 189, medal: "gold" }, unlockedStars: {}, date: 1705633368, type: "none", attemptNumber: 2, humanDate: "2024-01-19T03:02:48Z" },
              { data: { points: 83, medal: "wood" }, unlockedStars: {}, date: 1705633368, type: "none", attemptNumber: 3, humanDate: "2024-01-19T03:02:48Z" },
              {
                data: { points: 498, medal: "silver" },
                unlockedStars: {},
                date: 1705633368,
                type: "none",
                attemptNumber: 4,
                humanDate: "2024-01-19T03:02:48Z",
              },
              { data: { points: 93, medal: "silver" }, unlockedStars: {}, date: 1705633368, type: "none", attemptNumber: 5, humanDate: "2024-01-19T03:02:48Z" },
              { data: { points: 149, medal: "wood" }, unlockedStars: {}, date: 1705633368, type: "none", attemptNumber: 6, humanDate: "2024-01-19T03:02:48Z" },
              {
                data: { points: 367, medal: "bronze" },
                unlockedStars: {},
                date: 1705633368,
                type: "none",
                attemptNumber: 7,
                humanDate: "2024-01-19T03:02:48Z",
              },
              {
                data: { points: 344, medal: "silver" },
                unlockedStars: {},
                date: 1705633368,
                type: "none",
                attemptNumber: 8,
                humanDate: "2024-01-19T03:02:48Z",
              },
              { data: { points: 271, medal: "gold" }, unlockedStars: {}, date: 1705633368, type: "none", attemptNumber: 9, humanDate: "2024-01-19T03:02:48Z" },
              { data: { points: 79, medal: "wood" }, unlockedStars: {}, date: 1705633368, type: "none", attemptNumber: 10, humanDate: "2024-01-19T03:02:48Z" },
              {
                data: { points: 110, medal: "silver" },
                unlockedStars: {},
                date: 1705633368,
                type: "none",
                attemptNumber: 11,
                humanDate: "2024-01-19T03:02:48Z",
              },
              {
                data: { points: 477, medal: "silver" },
                unlockedStars: {},
                date: 1705633368,
                type: "none",
                attemptNumber: 12,
                humanDate: "2024-01-19T03:02:48Z",
              },
              {
                data: { points: 453, medal: "bronze" },
                unlockedStars: {},
                date: 1705633368,
                type: "none",
                attemptNumber: 13,
                humanDate: "2024-01-19T03:02:48Z",
              },
              { data: { points: 458, medal: "gold" }, unlockedStars: {}, date: 1705633368, type: "none", attemptNumber: 14, humanDate: "2024-01-19T03:02:48Z" },
              {
                data: { points: 65, medal: "silver" },
                unlockedStars: {},
                date: 1705633368,
                type: "none",
                attemptNumber: 15,
                humanDate: "2024-01-19T03:02:48Z",
              },
              {
                data: { points: 241, medal: "silver" },
                unlockedStars: {},
                date: 1705633368,
                type: "none",
                attemptNumber: 16,
                humanDate: "2024-01-19T03:02:48Z",
              },
              {
                data: { points: 285, medal: "bronze" },
                unlockedStars: {},
                date: 1705633368,
                type: "none",
                attemptNumber: 17,
                humanDate: "2024-01-19T03:02:48Z",
              },
              {
                data: { points: 296, medal: "silver" },
                unlockedStars: {},
                date: 1705633368,
                type: "none",
                attemptNumber: 18,
                humanDate: "2024-01-19T03:02:48Z",
              },
              { data: { points: 182, medal: "gold" }, unlockedStars: {}, date: 1705633368, type: "none", attemptNumber: 19, humanDate: "2024-01-19T03:02:48Z" },
              { data: { points: 139, medal: "gold" }, unlockedStars: {}, date: 1705633368, type: "none", attemptNumber: 20, humanDate: "2024-01-19T03:02:48Z" },
              {
                data: { points: 104, medal: "bronze" },
                unlockedStars: {},
                date: 1705633368,
                type: "none",
                attemptNumber: 21,
                humanDate: "2024-01-19T03:02:48Z",
              },
              { data: { points: 69, medal: "wood" }, unlockedStars: {}, date: 1705633368, type: "none", attemptNumber: 22, humanDate: "2024-01-19T03:02:48Z" },
              { data: { points: 390, medal: "wood" }, unlockedStars: {}, date: 1705633368, type: "none", attemptNumber: 23, humanDate: "2024-01-19T03:02:48Z" },
              {
                data: { points: 387, medal: "bronze" },
                unlockedStars: {},
                date: 1705633368,
                type: "none",
                attemptNumber: 24,
                humanDate: "2024-01-19T03:02:48Z",
              },
              {
                data: { points: 180, medal: "silver" },
                unlockedStars: {},
                date: 1705633368,
                type: "none",
                attemptNumber: 25,
                humanDate: "2024-01-19T03:02:48Z",
              },
            ],
            aggregate: { bestType: "none", mosttimespan: 1705633368, attemptCount: 25, passed: false, completed: false },
            leaderboards: { recent: [25, 24, 23, 22, 21] },
          },
        },
        hasUserSettings: true,
        name: "missions.west_coast_usa.collection.downtownrush.title",
        userSettings: [{ values: [{ v: 1, l: "Hirochi Aurata " }], value: 1, type: "select", key: "setupModuleVehicles", label: "ui.busRoute.vehicle" }],
        description: "missions.west_coast_usa.collection.downtownrush.description",
        id: "west_coast_usa/collection/002-downtown",
        currentProgressKey: "default",
        formattedProgress: {
          formattedProgressByKey: {
            default: {
              attempts: { rows: {}, labels: ["#", "", "", "bigMap.progressLabels.markersCollected"] },
              ownAggregate: [
                { value: { text: "25" }, label: "Attempts" },
                { value: { text: "-" }, label: "bigMap.progressLabels.bestMarkersCollected" },
              ],
            },
          },
          progressKeyTranslations: { default: "missions.progressKeyLabels.default" },
          defaultProgressKey: "default",
          allProgressKeys: ["default"],
          unlockedStars: {
            stars: [
              {
                rewards: {},
                defaultStarIndex: 1,
                unlocked: false,
                isDefaultStar: true,
                key: "survivalMarkersBronze",
                label: {
                  txt: "missions.collect.stars.survivalMarkersBronze",
                  context: {
                    attackRecoveryBonus: "0",
                    survivalTime: "340",
                    attackTimeBronze: "120",
                    attackRecoverySilver: "5",
                    attackRecoveryBronze: "10",
                    attackTimeBonus: "45",
                    survivalRecoveries: "1",
                    survivalMarkersBonus: "60",
                    attackRecoveryGold: "1",
                    attackTimeGold: "60",
                    introText: "missions.west_coast_usa.collection.downtownrush.introText",
                    resourceMode: "time",
                    markerMode: "survival",
                    markerFile: "/art/shapes/collectible/s_collect_money_sack.dae",
                    survivalMarkersSilver: "40",
                    attackTimeSilver: "90",
                    survivalMarkersGold: "50",
                    survivalMarkersBronze: "30",
                  },
                },
              },
              {
                rewards: {},
                defaultStarIndex: 2,
                unlocked: false,
                isDefaultStar: true,
                key: "survivalMarkersSilver",
                label: {
                  txt: "missions.collect.stars.survivalMarkersSilver",
                  context: {
                    attackRecoveryBonus: "0",
                    survivalTime: "340",
                    attackTimeBronze: "120",
                    attackRecoverySilver: "5",
                    attackRecoveryBronze: "10",
                    attackTimeBonus: "45",
                    survivalRecoveries: "1",
                    survivalMarkersBonus: "60",
                    attackRecoveryGold: "1",
                    attackTimeGold: "60",
                    introText: "missions.west_coast_usa.collection.downtownrush.introText",
                    resourceMode: "time",
                    markerMode: "survival",
                    markerFile: "/art/shapes/collectible/s_collect_money_sack.dae",
                    survivalMarkersSilver: "40",
                    attackTimeSilver: "90",
                    survivalMarkersGold: "50",
                    survivalMarkersBronze: "30",
                  },
                },
              },
              {
                rewards: {},
                defaultStarIndex: 3,
                unlocked: false,
                isDefaultStar: true,
                key: "survivalMarkersGold",
                label: {
                  txt: "missions.collect.stars.survivalMarkersGold",
                  context: {
                    attackRecoveryBonus: "0",
                    survivalTime: "340",
                    attackTimeBronze: "120",
                    attackRecoverySilver: "5",
                    attackRecoveryBronze: "10",
                    attackTimeBonus: "45",
                    survivalRecoveries: "1",
                    survivalMarkersBonus: "60",
                    attackRecoveryGold: "1",
                    attackTimeGold: "60",
                    introText: "missions.west_coast_usa.collection.downtownrush.introText",
                    resourceMode: "time",
                    markerMode: "survival",
                    markerFile: "/art/shapes/collectible/s_collect_money_sack.dae",
                    survivalMarkersSilver: "40",
                    attackTimeSilver: "90",
                    survivalMarkersGold: "50",
                    survivalMarkersBronze: "30",
                  },
                },
              },
            ],
            defaultUnlockedStarCount: 0,
            totalStars: 3,
            totalUnlockedStarCount: 0,
          },
        },
        defaultUserSettings: { setupModuleVehicles: 1 },
        hasUserSettingsUnlocked: true,
        leaderboardKey: "highscore",
        devMission: false,
        unlocks: {
          visible: true,
          depth: 5,
          startable: true,
          backward: {},
          branchTags: {},
          maxBranchlevel: 0,
          startableDetails: { met: true, condition: { type: "automatic" }, label: "missions.missions.unlock.missing" },
          forward: {},
        },
        missionTypeLabel: "bigMap.missionLabels.collection",
        additionalAttributes: [{ icon: "flag", valueKey: "High", labelKey: "Difficulty" }],
        previews: ["images/noimage.png"],
      },
      {
        progress: {
          "1-false-false": { attempts: {}, aggregate: { bestType: "none", passed: false, completed: false, attemptCount: 0 }, leaderboards: { recent: {} } },
        },
        hasUserSettings: true,
        name: "missions.west_coast_usa.timeTrial.Street1.title",
        userSettings: [
          { values: [{ type: "player", v: 1, l: "Player Vehicle" }], value: 1, type: "select", key: "setupModuleVehicles", label: "ui.busRoute.vehicle" },
          { min: 1, value: 1, max: 3, type: "int", isProgressKey: true, key: "laps", label: "missions.missions.general.userSettings.laps" },
          { value: false, type: "bool", isProgressKey: true, key: "reverse", label: "missions.missions.timeTrial.userSettings.reverse" },
          { value: false, type: "bool", isProgressKey: true, key: "rolling", label: "missions.missions.timeTrial.userSettings.rollingStart" },
        ],
        description: "missions.west_coast_usa.timeTrial.Street1.description",
        id: "west_coast_usa/testTimeTrial/007-Street",
        currentProgressKey: "1-false-false",
        formattedProgress: {
          formattedProgressByKey: {
            "1-false-false": {
              attempts: { rows: {}, labels: ["#", "", "", "bigMap.progressLabels.time", "missions.missions.general.penaltyTime"] },
              ownAggregate: [
                { value: { text: "0" }, label: "Attempts" },
                { value: { text: "-" }, label: "bigMap.progressLabels.bestTime" },
              ],
            },
          },
          progressKeyTranslations: { "1-false-false": { txt: "missions.timeTrials.progressKeyLabels.general", context: { laps: "1" } } },
          defaultProgressKey: "1-false-false",
          allProgressKeys: ["1-false-false"],
          unlockedStars: { disabled: true },
        },
        defaultUserSettings: { rolling: false, setupModuleVehicles: 1, laps: 1, reverse: false },
        hasUserSettingsUnlocked: true,
        leaderboardKey: "highscore",
        devMission: false,
        unlocks: {
          visible: true,
          depth: 5,
          startable: true,
          backward: {},
          branchTags: {},
          maxBranchlevel: 0,
          startableDetails: { met: true, condition: { type: "automatic" }, label: "missions.missions.unlock.missing" },
          forward: {},
        },
        missionTypeLabel: "bigMap.missionLabels.testTimeTrial",
        additionalAttributes: {},
        previews: ["images/noimage.png"],
      },
      {
        progress: {
          "1-false-false": { attempts: {}, aggregate: { bestType: "none", passed: false, completed: false, attemptCount: 0 }, leaderboards: { recent: {} } },
        },
        hasUserSettings: true,
        name: "missions.west_coast_usa.timeTrial.Street1.title",
        userSettings: [
          { values: [{ type: "player", v: 1, l: "Player Vehicle" }], value: 1, type: "select", key: "setupModuleVehicles", label: "ui.busRoute.vehicle" },
          { min: 1, value: 1, type: "int", isProgressKey: true, key: "laps", label: "missions.missions.general.userSettings.laps" },
          { value: false, type: "bool", isProgressKey: true, key: "reverse", label: "missions.missions.timeTrial.userSettings.reverse" },
          { value: false, type: "bool", isProgressKey: true, key: "rolling", label: "missions.missions.timeTrial.userSettings.rollingStart" },
        ],
        description: "missions.west_coast_usa.timeTrial.Street1.description",
        id: "west_coast_usa/timeTrial/007-Street",
        currentProgressKey: "1-false-false",
        formattedProgress: {
          formattedProgressByKey: {
            "1-false-false": {
              attempts: { rows: {}, labels: ["#", "", "", "bigMap.progressLabels.time", "missions.missions.general.penaltyTime"] },
              ownAggregate: [
                { value: { text: "0" }, label: "Attempts" },
                { value: { text: "-" }, label: "bigMap.progressLabels.bestTime" },
              ],
            },
          },
          progressKeyTranslations: { "1-false-false": { txt: "missions.timeTrials.progressKeyLabels.general", context: { laps: "1" } } },
          defaultProgressKey: "1-false-false",
          allProgressKeys: ["1-false-false"],
          unlockedStars: { disabled: true },
        },
        defaultUserSettings: { rolling: false, setupModuleVehicles: 1, laps: 1, reverse: false },
        hasUserSettingsUnlocked: true,
        leaderboardKey: "highscore",
        devMission: false,
        unlocks: {
          visible: true,
          depth: 5,
          startable: true,
          backward: {},
          branchTags: {},
          maxBranchlevel: 0,
          startableDetails: { met: true, condition: { type: "automatic" }, label: "missions.missions.unlock.missing" },
          forward: {},
        },
        missionTypeLabel: "bigMap.missionLabels.timeTrial",
        additionalAttributes: {},
        previews: ["test/images/car-image.png", "images/noimage.png"],
      },
    ],
  },
}
