import { defineConfig } from "vite"
import path from "path"
import fs from "fs-extra"
import vue from "@vitejs/plugin-vue"
import envCompatible from "vite-plugin-env-compatible"
import { createHtmlPlugin } from "vite-plugin-html"
import { viteCommonjs } from "@originjs/vite-plugin-commonjs"
import { visualizer } from "rollup-plugin-visualizer"

const GAMEFILE_DIRS = [
  "/locales/",
  "/ui/",
  "/gameplay/",
  "/levels/",
]
const GAMEFILE_FILES = [
  "/licenses.txt",
]
const GAMEFILE_RGX = /^\/((locales|ui|gameplay|levels)\/|licenses\.txt$)/

const isProd = process.env.NODE_ENV === "production"
const isDev = !isProd

function serveGameFiles() {
  function register(server) {
    server.middlewares.use((req, res, next) => {
      let filePath = decodeURI(req.url)
      // reject unknown
      if (!filePath || !GAMEFILE_DIRS.some(path => filePath.startsWith(path)) && !GAMEFILE_FILES.some(file => filePath === file)) return next()
      filePath = path.resolve(__dirname, "../.." + filePath)
      // reject non-existent
      if (!fs.existsSync(filePath)) return next()
      // add CORS headers
      res.setHeader("Access-Control-Allow-Origin", "local://local")
      res.setHeader("Access-Control-Allow-Methods", "GET, HEAD")
      res.setHeader("Access-Control-Allow-Headers", "Content-Type")
      res.setHeader("Access-Control-Allow-Credentials", "true")
      // return file contents
      res.writeHead(200)
      fs.createReadStream(filePath).pipe(res)
    })
  }
  return {
    name: "serve-game-files",
    configureServer: register,
    configurePreviewServer: register,
  }
}

function replaceCode(replacements) {
  replacements = replacements.map(r => ({
    from: r.from,
    to: isProd ? r.toProd : r.toDev,
  }))
  return {
    name: "replace-code",
    enforce: "pre",
    transform(code, id) {
      let out = code
      for (const replacement of replacements) {
        out = out.replace(replacement.from, replacement.to)
      }
      return out === code ? null : { code: out, map: null }
    },
    transformIndexHtml(html) {
      for (const replacement of replacements) {
        html = html.replace(replacement.from, replacement.to)
      }
      return html
    },
  }
}

/**
 * Plugin to automatically export components, directives, etc
 * @param {*} srcDir - Source directory to scan files in
 * @param {RegExp} pattern - Pattern to match for validation and replacement. Note: if pattern is not for vue files, specify multiple file extensions that include vue for demos to work.
 * @param {string|function} replace - Replacement for the file name
 * @returns {object} - Plugin thing
 */
function autoExport(srcDir, pattern, replace) {
  const srcPath = path.resolve(__dirname, "src", srcDir)

  const outFileName = "index.gen.js"
  const outFilePath = path.resolve(srcPath, outFileName)

  const generate = () => {
    const src = [
      "// Do not edit!",
      "// This file is auto-generated by vite.config.js",
      "",
    ]
    const names = []

    // sources
    fs.readdirSync(srcPath)
      .forEach(file => {
        let name = file
        if (name === outFileName) return
        if (name.includes(".dev.")) {
          if (!isDev) return
          name = name.replace(".dev.", ".")
        }
        if (!pattern.test(name)) return
        name = name.replace(pattern, replace)
        names.push(name)
        src.push(`export { default as ${name} } from "./${file}"`)
      })

    // demos
    src.push("", "export const DEMOS = import.meta.hot ? {")
    fs.readdirSync(path.resolve(srcPath, "demos"))
      .filter(f => f.endsWith(".vue")) // demos are always .vue
      .forEach(file => {
        let name = file
        if (!name.includes("_demo.")) return
        name = name.replace("_demo.", ".")
        if (!pattern.test(name)) return
        name = name.replace(pattern, replace)
        if (!names.includes(name)) {
          console.warn(`Found demo for non-existent component ${name}`)
          return
        }
        src.push(`  ${name}: import("./demos/${file}"),`)
      })
    src.push("} : {}", "")

    // export
    fs.writeFileSync(outFilePath, src.join("\n"))
    // console.log(`Generated ${outFilePath}`)
  }

  return {
    name: "bng-auto-export::" + srcDir,
    buildStart() {
      generate()
    },
    handleHotUpdate(ctx) {
      if (ctx.file.startsWith(srcPath) && ctx.file !== path.resolve(srcPath, outFileName)) {
        generate()
      }
    },
  }
}

// https://vitejs.dev/config/
export default defineConfig({
  publicDir: false,

  ...(isProd && { base: "/local/ui/ui-vue/" }),

  define: {
    __VUE_OPTIONS_API__: "true",
    __VUE_PROD_DEVTOOLS__: "false",
    __VUE_PROD_HYDRATION_MISMATCH_DETAILS__: "false",
  },

  resolve: {
    alias: [
      {
        find: /^~/,
        replacement: "",
      },
      {
        find: "@",
        replacement: path.resolve(__dirname, "src"),
      },
    ],
    extensions: [".mjs", ".cjs", ".js", ".ts", ".jsx", ".tsx", ".json"],
  },

  plugins: [
    // visualizer(), // renders the bundle breakdown to stats.html
    serveGameFiles(),
    replaceCode([
      // JS - DEV_ONLY
      {
        from: /(\/\/\s*?DEV_ONLY\s*?>>[.\s\S]*?\/\/\s*?<<\s*?END_DEV_ONLY)/gm,
        toProd: "",
        toDev: "$1",
      },
      // HTML - DEV_ONLY
      {
        from: /(<!--\s*?DEV_ONLY\s*?>>\s*?-->[.\s\S]*?<!--\s*?<<\s*?END_DEV_ONLY\s*?-->)/gm,
        toProd: "",
        toDev: "$1",
      },
      // CSS - DEV_ONLY
      {
        from: /(\/\*\s*?DEV_ONLY\s*?>>\s*?\*\/[.\s\S]*?\/\*\s*?<<\s*?END_DEV_ONLY\s*?\*\/)/gm,
        toProd: "",
        toDev: "$1",
      },
    ]),
    // bngSomeThing.vue > BngSomeThing
    autoExport("common/components/base", /^bng([a-z\d]+)\.vue$/i, "Bng$1"),
    // bngSomeThing.vue in appsUtilities > BngSomeThing
    autoExport("common/components/appsUtilities", /^bng([a-z\d]+)\.vue$/i, "Bng$1"),
    // someThing.vue > SomeThing
    autoExport("common/components/utility", /^(.)([a-z\d]+)\.vue$/i, (_, n, ame) => n.toUpperCase() + ame),
    // BngSomeThing.js > vBngSomeThing
    autoExport("common/directives", /^Bng([a-z\d]+)\.(?:js|vue)$/i, "vBng$1"),
    // someThing.vue > SomeThing
    autoExport("common/layouts", /^([a-z\d])([a-z\d]+)\.vue$/i, (_, n, ame) => n.toUpperCase() + ame),
    vue(),
    viteCommonjs(),
    envCompatible(),
    createHtmlPlugin({
      inject: {
        data: {
          title: "ui-vue",
        },
      },
    }),
  ],

  server: {
    strictPort: false,
    port: 9000,
    host: "localhost",
    https: false,
    cors: {
      origin: ["local://local", "http://localhost:9000"],
      methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
      credentials: true
    },
    hmr: {
      host: "localhost",
      port: 9000,
    },
    // this thing allows unobstructed browser access to files
    proxy: [...GAMEFILE_DIRS, ...GAMEFILE_FILES].reduce((res, path) => ({
      ...res, [path]: { changeOrigin: true }
    }), {}),
  },

  build: {
    target: "esnext",
    sourcemap: "hidden",
    rollupOptions: {
      output: {
        entryFileNames: `[name].js`,
        chunkFileNames: `[name].js`,
        assetFileNames: `[name].[ext]`,
      },
      onwarn(warning, warn) {
        if (warning.code === "EVAL") return
        warn(warning)
      },
      // external: [/^\/ui/],
      external: [GAMEFILE_RGX],
    },
    chunkSizeWarningLimit: 100 * 1024, // in KB
  },
})