// Do not edit!
// This file is auto-generated by vite.config.js

export { default as Accordion } from "./accordion.vue"
export { default as AccordionItem } from "./accordionItem.vue"
export { default as AccordionTree } from "./accordionTree.vue"
export { default as AspectRatio } from "./aspectRatio.vue"
export { default as Carousel } from "./carousel.vue"
export { default as CarouselItem } from "./carouselItem.vue"
export { default as Drawer } from "./drawer.vue"
export { default as DynamicComponent } from "./dynamicComponent.vue"
export { default as Shelf } from "./shelf.vue"
export { default as SlotSwitcher } from "./slotSwitcher.vue"
export { default as Tab } from "./tab.vue"
export { default as TabList } from "./tabList.vue"
export { default as Tabs } from "./tabs.vue"
export { default as TextScroller } from "./textScroller.vue"
export { default as Tree } from "./tree.vue"
export { default as TreeNode } from "./treeNode.vue"

export const DEMOS = import.meta.hot ? {
  AccordionItem: import("./demos/accordionItem_demo.vue"),
  AccordionTree: import("./demos/accordionTree_demo.vue"),
  Accordion: import("./demos/accordion_demo.vue"),
  AspectRatio: import("./demos/aspectRatio_demo.vue"),
  CarouselItem: import("./demos/carouselItem_demo.vue"),
  Carousel: import("./demos/carousel_demo.vue"),
  Drawer: import("./demos/drawer_demo.vue"),
  DynamicComponent: import("./demos/dynamicComponent_demo.vue"),
  Shelf: import("./demos/shelf_demo.vue"),
  SlotSwitcher: import("./demos/slotSwitcher_demo.vue"),
  Tabs: import("./demos/tabs_demo.vue"),
  TextScroller: import("./demos/textScroller_demo.vue"),
  Tree: import("./demos/tree_demo.vue"),
} : {}
