// Do not edit!
// This file is auto-generated by vite.config.js

export { default as LayoutEmpty } from "./layoutEmpty.vue"
export { default as LayoutSingle } from "./layoutSingle.vue"

export const DEMOS = import.meta.hot ? {
  LayoutSingle: import("./demos/layoutSingle_demo.vue"),
} : {}
