// Do not edit!
// This file is auto-generated by vite.config.js

export { default as vBngAutoScroll } from "./BngAutoScroll.js"
export { default as vBngBlur } from "./BngBlur.js"
export { default as vBngClick } from "./BngClick.js"
export { default as vBngDisabled } from "./BngDisabled.js"
export { default as vBngDoubleClick } from "./BngDoubleClick.js"
export { default as vBngDraggable } from "./BngDraggable.js"
export { default as vBngFocusCapture } from "./BngFocusCapture.js"
export { default as vBngFocusIf } from "./BngFocusIf.js"
export { default as vBngFrustumMover } from "./BngFrustumMover.js"
export { default as vBngHighlighter } from "./BngHighlighter.js"
export { default as vBngLazyImage } from "./BngLazyImage.js"
export { default as vBngOcclusionWatcher } from "./BngOcclusionWatcher.js"
export { default as vBngOnUiNav } from "./BngOnUiNav.js"
export { default as vBngOnUiNavFocus } from "./BngOnUiNavFocus.js"
export { default as vBngPanel } from "./BngPanel.js"
export { default as vBngPopover } from "./BngPopover.js"
export { default as vBngRelativeTime } from "./BngRelativeTime.js"
export { default as vBngScopedNav } from "./BngScopedNav.js"
export { default as vBngSoundClass } from "./BngSoundClass.js"
export { default as vBngTextInput } from "./BngTextInput.js"
export { default as vBngTooltip } from "./BngTooltip.js"
export { default as vBngUiNavFocus } from "./BngUiNavFocus.js"
export { default as vBngUiNavLabel } from "./BngUiNavLabel.js"
export { default as vBngUiNavScroll } from "./BngUiNavScroll.js"
export { default as vBngVisibility } from "./BngVisibility.js"

export const DEMOS = import.meta.hot ? {
  vBngAutoScroll: import("./demos/BngAutoScroll_demo.vue"),
  vBngBlur: import("./demos/BngBlur_demo.vue"),
  vBngClick: import("./demos/BngClick_demo.vue"),
  vBngDisabled: import("./demos/BngDisabled_demo.vue"),
  vBngDoubleClick: import("./demos/BngDoubleClick_demo.vue"),
  vBngFocusCapture: import("./demos/BngFocusCapture_demo.vue"),
  vBngFocusIf: import("./demos/BngFocusIf_demo.vue"),
  vBngFrustumMover: import("./demos/BngFrustumMover_demo.vue"),
  vBngHighlighter: import("./demos/BngHighlighter_demo.vue"),
  vBngOnUiNav: import("./demos/BngOnUiNav_demo.vue"),
  vBngPanel: import("./demos/BngPanel_demo.vue"),
  vBngPopover: import("./demos/BngPopover_demo.vue"),
  vBngRelativeTime: import("./demos/BngRelativeTime_demo.vue"),
  vBngScopedNav: import("./demos/BngScopedNav_demo.vue"),
  vBngSoundClass: import("./demos/BngSoundClass_demo.vue"),
  vBngTooltip: import("./demos/BngTooltip_demo.vue"),
} : {}
