// Credits data

export default
[
    { translateId: 'ui.credits.programmers', members: [
        {first: 'Thomas',        last: 'Fischer',          aka: 'tdev',          title: 'CEO'},
        {first: 'Lefteris',      last: 'Stamatogiannakis', aka: 'estama',        title: 'CTO / Physics / Sound / AI'},
        {first: 'Luis',          last: 'Anton Rebollo',    aka: 'Souga',         title: 'Lead Render Developer'},
        {first: 'Alex',          last: 'Spodheim',         aka: 'CrankyCleric',  title: 'Developer'},
        {first: 'Ananda Neelam', last: 'Thathayya',        aka: 'Nadeox1',       title: 'Technical Artist'},
        {first: 'Andrew',        last: 'Kabakwu',          aka: '',              title: 'Developer'},
        {first: 'Bruno',         last: 'Gonzalez Campo',   aka: 'stenyak',       title: 'Lead Game Engine Developer'},
        {first: 'Cosmin',        last: 'Traian',           aka: '',              title: 'Developer'},
        {first: 'Emre',          last: 'Kut',              aka: '',              title: 'Developer'},
        {first: 'Felix',         last: 'Unger',            aka: '',              title: 'Developer'},
        {first: 'George',        last: 'Troulitakis',      aka: 'AtmanB',        title: 'Developer'},
        {first: 'Guillem',       last: 'Ortega',           aka: '',              title: 'Developer'},
        {first: 'Logane',        last: 'Ramez',            aka: 'Gadoy',         title: 'Developer'},
        {first: 'Lorenzo',       last: 'Bartali',          aka: '',              title: 'AI Developer'},
        {first: 'Ludger',        last: 'Meyer-Wülfing',    aka: 'meywue',        title: 'Developer'},
        {first: 'Nicusor',       last: 'Nedelcu',          aka: '',              title: 'Tools Developer'},
        {first: 'Panos',         last: 'Karabelas',        aka: '',              title: 'Developer'},
        {first: 'Patrick ',      last: 'Schrangl',         aka: '',              title: 'Simulation Software Engineer'},
        {first: 'Petros',        last: 'Kondylis',         aka: '',              title: 'AI Developer'},
        {first: 'Ronny',         last: 'Nowak',            aka: '',              title: 'Developer'},
        {first: 'Thomas',        last: 'Portassau',        aka: 'thomatoes50',   title: 'Developer'},
        {first: 'Thomas',        last: 'Wilczynski',       aka: 'Gamergull',     title: 'Developer'},
        {first: 'Timo',          last: 'Stabbert',         aka: '',              title: 'Gameplay Dev Lead'},
        {first: 'Valery',        last: 'Dolotin',          aka: '',              title: 'AI Developer'},
        {first: 'Daniel',        last: 'Wakefield',        aka: '',              title: 'Developer'},
    ]},
    { translateId: 'ui.credits.vehiclePhysics', members: [
        {first: 'Fabian',        last: 'Enkler',           aka: 'Diamondback',   title: 'Vehicle Systems Lead'},
        {first: 'Angelo',        last: 'Matteo',           aka: 'angelo234',     title: 'Tools Developer'},
        {first: 'Aubrey',        last: 'Percival',         aka: '',              title: 'Vehicle Physics Engineer'},
        {first: 'Bobby',         last: 'Villeneuve',       aka: 'Binkey',        title: 'Vehicle Physics Engineer'},
        {first: 'Brian',         last: 'Rickets',          aka: '',              title: 'Vehicle Systems Engineer'},
        {first: 'Corey',         last: 'Bergerud',         aka: 'Goosah',        title: 'Vehicle Physics Engineer'},
        {first: 'Davide',        last: 'Serpi',            aka: '',              title: 'Vehicle Dynamics Control Intern'},
        {first: 'Efe Can',       last: 'Kiraz',            aka: 'RenAzuma66',    title: 'Vehicle Physics Engineer'},
        {first: 'Grzegorz',      last: 'Węgrzyn',          aka: 'AiTorror',      title: 'Vehicle Physics Engineer / QA'},
        {first: 'Jack',          last: 'Jermany',          aka: '',              title: 'Vehicle Physics Engineer / QA'},
        {first: 'Oliver',        last: 'Čajka',            aka: 'MRcrash',       title: 'Vehicle Physics Engineer'},
        {first: 'Piotr',         last: 'Gajek',            aka: 'Agent_Y',       title: 'Vehicle Physics Engineer / QA'},
        {first: 'Toma Ioan',     last: ' Turcu',           aka: '',              title: 'Vehicle Physics Engineer'},
        {first: 'Quinn',         last: 'Howling',          aka: 'SpeedHero',     title: 'Vehicle Physics Designer'},
    ]},
    { translateId: 'ui.credits.vehicleArt', members: [
        {first: 'Gabriel',       last: 'Fink',       aka: 'gabester',   title: 'Vehicle Art Director'},
        {first: 'Jared',         last: 'Samuelson',  aka: '',           title: 'Vehicle Team Lead / Subaru Expert'},
        {first: 'Alexandr',      last: 'Shesternin', aka: '',           title: '3D Vehicle Artist'},
        {first: 'Andreas',       last: 'Focht',      aka: '',           title: 'Vehicle Concept Artist'},
        {first: 'Daniel',        last: 'Russo',      aka: 'A3DR',       title: '3D Vehicle Artist'},
        {first: 'Dennis',        last: 'Mateja',     aka: 'NinetyNine', title: 'Vehicle Designer'},
        {first: 'Manish',        last: 'Rawat',      aka: '',           title: '3D Vehicle Artist'},
    ]},
    { translateId: 'ui.credits.environmentArtists', members: [
        {first: 'Sam',         last: 'Hutchinson',     aka: 'LJFHutch',    title: 'Environment Art Director'},
        {first: 'Luca',        last: 'Brighi',         aka: '',            title: 'Lead 3D Environment Artist'},
        {first: 'Huiqin',      last: 'Li',             aka: '',            title: '3D Environment Artist'},
        {first: 'Sebastien',   last: 'Pelletier',      aka: 'DoullPepper', title: '3D Environment Artist'},
    ]},
    { translateId: 'ui.credits.conceptArtists', members: [
        {first: 'Mary Jane',   last: 'Pajaron',         aka: '', title: '2D Concept Artist'},
    ]},
    { translateId: 'ui.credits.gameDesigners', members: [
        {first: 'James',               last: 'Heslop',     aka: 'Krallopian',    title: 'Game Design Lead'},
        {first: 'Alex',                last: 'Bird',       aka: '',              title: 'Gameplay Developer'},
        {first: 'Rob',                 last: 'Herridge',   aka: 'HighDef',       title: 'Gameplay Developer / QA'},
    ]},
    { translateId: 'ui.credits.ui', members: [
        {first: 'Pavel',          last: 'Tiunov',           aka: 'Dizboosta',     title: 'UI Lead'},
        {first: 'Destiny',        last: 'Abellana',         aka: '',              title: 'Developer'},
        {first: 'Stani',          last: 'Tolmacheva',       aka: 'Snowly',        title: 'Developer'},
    ]},
    { translateId: 'ui.credits.sound', members: [
        {first: 'Mark',           last: 'Knight',    aka: 'TDK', title: 'Audio Designer'},
        {first: 'Sebastian',      last: 'Emling',    aka: '',    title: 'Audio Designer'},
        {first: 'Jethro',         last: 'Dunn',      aka: '',    title: 'Audio Outsourcer'},
        {first: 'Max',            last: 'Schumann',  aka: '',    title: 'Audio Outsourcer'},
    ]},
    { translateId: 'ui.credits.qa', members: [
        {first: 'Colin',          last: 'Wenz',         aka: 'synsol',     title: 'QA Lead'},
        {first: 'Przemysław',     last: 'Wolny',        aka: 'Car_Killer', title: 'QA / Mod Support'},
    ]},
    { translateId: 'ui.credits.production', members: [
        {first: 'Ryan',           last: 'Dunne',               aka: '',      title: 'Producer'},
    ]},
    { translateId: 'ui.credits.sysops', members: [
        {first: 'Charalampos',    last: 'Tsipizidis',    aka: '', title: 'System Administrator'},
        {first: 'Dimitrios',      last: 'Folias',        aka: '', title: 'System Administrator'},
    ]},
    { translateId: 'ui.credits.comms', members: [
        {first: 'Nataliia',     last: 'Dmytriievska',    aka: 'Leeloo',         title: 'Communications & Marketing Lead'},
        {first: 'Bernice',      last: 'Mills',           aka: 'Bee',            title: 'Community Support & Marketing Specialist'},
        {first: 'Mariia',       last: 'Gumarova',        aka: 'Fluffy Panda',   title: 'Customer Support & Marketing Specialist'},
        {first: 'Slawomir',     last: 'Niemczyk',        aka: 'Sedricoo',       title: 'Community Coordinator'},
        {first: 'Vincent',      last: 'Liu',             aka: '',               title: 'Community & Marketing Specialist (APAC)'},
    ]},
    { translateId: 'ui.credits.research', members: [
        {first: 'Chrysanthi',       last: 'Papamichail',    aka: '',          title: 'Lead Research Software Engineer'},
        {first: 'Abdulrahman',      last: 'Saeed',          aka: '',          title: 'Research Software Engineer'},
        {first: 'Adam',             last: 'Ivora',          aka: '',          title: 'Research Software Engineer'},
        {first: 'David',            last: 'Stark',          aka: '',          title: 'Research Software Engineer'},
        {first: 'Florian',          last: 'Faistauer',      aka: '',          title: 'Vehicle Simulation Expert'},
        {first: 'Gabriel Puretas',  last: 'Moral',          aka: '',          title: 'UX Intern'},
        {first: 'Sayali',           last: 'Rajhans',        aka: '',          title: 'Research Software Engineer'},
        {first: 'Iskren',           last: 'Rusimov',        aka: '',          title: 'Research Software Engineer Intern'},
    ]},
    { translateId: 'ui.credits.organization', members: [
        {first: 'Christoforos',   last: 'Lambrianidis',     aka: '',          title: 'CFO'},
        {first: 'Joseph',         last: 'Inba Raj',         aka: '',          title: 'HR & Talent Acquisition Lead'},
        {first: 'Cecilia',        last: 'Sari',             aka: '',          title: 'Recruitment Specialist'},
        {first: 'Dimitra',        last: 'Litsardou',        aka: 'Thamy',     title: 'EU / Co-funding Advisory Specialist'},
        {first: 'Eva',            last: 'Pigova',           aka: '',          title: 'Senior Program Manager'},
        {first: 'Maria',          last: 'Kosmachevskaya',   aka: '',          title: 'Business Development Intern'},
        {first: 'Özge',           last: 'Altinkaya Erkok',  aka: '',          title: 'Communication Consultant'},
        {first: 'Renars',         last: 'Skesteris',        aka: '',          title: 'Business Development Intern'},
        {first: 'Sabrina',        last: 'Wee',              aka: '',          title: 'Business Development Manager'},
        {first: 'Sandra',         last: 'Campos',           aka: '',          title: 'Accounting Assistant'},
        {first: 'Ulrike',         last: 'Lentz',            aka: '',          title: 'Executive Assistant'},
    ]},
    { translateId: 'ui.credits.additionalVehiclePhysics', members: [
        {first: 'Will',           last: 'Leader',           aka: '',          title: 'Off-road Suspension Development and Vehicle Dynamics'},
    ]},
    { translateId: 'ui.credits.additionalVehicleArt', members: [
        {first: 'Ashish',         last: 'Singh',            aka: '',          title: 'Freelance 3D Vehicle Artist'},
        {first: 'Juan Manuel',    last: 'Orcellet',         aka: '',          title: 'Freelance 3D Vehicle Artist'},
        {first: 'M. Yusuf',       last: 'Bolukbasi',        aka: '',          title: 'Freelance Vehicle Artist'},
        {first: 'Naman',          last: 'Deep',             aka: '',          title: 'Freelance 3D Vehicle Artist'},
    ]},
    { translateId: 'ui.credits.externalContributors', members: [
        {first: 'Da',          last: 'Li',          aka: '',           title: ''},
        {first: 'Ruhmit',      last: 'Sahu ',       aka: '',           title: ''},
    ]},
    { translateId: 'ui.credits.formerEmployee', members: [
        {first: 'Aaron',         last: 'Sutcliffe',         aka: '',        title: 'Developer / Vehicle Creation'},
        {first: 'Alex',          last: 'Raskin',            aka: '',        title: 'DevOps Engineer'},
        {first: 'Artem',         last: 'Arbatskii',         aka: '',        title: 'Developer'},
        {first: 'Arturo',        last: 'Campos',            aka: '',        title: 'Developer'},
        {first: 'Ben',           last: 'Payne',             aka: '',        title: 'Developer'},
        {first: 'Boluwatife',    last: 'Falaye',            aka: '',        title: 'Developer'},
        {first: 'Clément',       last: 'Roche',             aka: '',        title: 'Developer'},
        {first: 'Edelmar',       last: 'Schneider',         aka: '',        title: 'Developer'},
        {first: 'Eike',          last: 'Externest',         aka: '',        title: 'Developer'},
        {first: 'Jali',          last: 'Hautala',           aka: 'Jalkku',  title: 'Developer'},
        {first: 'Jeremy',        last: 'Lu',                aka: '',        title: 'Developer'},
        {first: 'John',          last: 'Beinecke',          aka: '',        title: 'Developer'},
        {first: 'Juan',          last: 'Mendez',            aka: '',        title: 'Developer'},
        {first: 'Leander',       last: 'Beernaert',         aka: '',        title: 'Game Engine Developer'},
        {first: 'Marc',          last: 'Müller',            aka: '',        title: 'Developer'},
        {first: 'Mark',          last: 'Vince',             aka: '',        title: 'Developer'},
        {first: 'Matti',         last: 'Yrjänheikki',       aka: 'Masa',    title: 'Developer'},
        {first: 'Max',           last: 'Razer',             aka: '',        title: 'Developer'},
        {first: 'Mayowa David',  last: 'Abogunrin',         aka: '',        title: 'Developer'},
        {first: 'Moncef',        last: 'Slimane',           aka: '',        title: 'Developer'},
        {first: 'Nourelhoda',    last: 'Mohamed',           aka: '',        title: 'Developer'},
        {first: 'Pascale',       last: 'Maul',              aka: '',        title: 'Developer'},
        {first: 'Paul',          last: 'De Almeida',        aka: '',        title: 'AI Developer'},
        {first: 'Paul',          last: 'Görs',              aka: '',        title: 'Developer'},
        {first: 'Peter',         last: 'Landwehr',          aka: '',        title: 'Developer'},
        {first: 'Petteri',       last: 'Koivumäki',         aka: '',        title: 'Developer'},
        {first: 'Vasilis',       last: 'Douvaras',          aka: '',        title: 'Developer'},
        {first: 'Vatroslav ',    last: 'Bodrozic',          aka: '',        title: 'Developer'},
        {first: 'Waldemar',      last: 'Zeitler',           aka: '',        title: 'Developer'},
        {first: 'Xiaoyi',        last: 'Wang',              aka: '',        title: 'Developer'},
        {first: '',              last: '',                  aka: '',        title: ''},
        {first: 'Adrian',        last: 'Baboi',             aka: '',        title: 'Vehicle Creation'},
        {first: 'Brandon',       last: 'Proulx',            aka: 'Hondune', title: 'Vehicle Creation'},
        {first: 'Carlos',        last: 'Bergillos Varela',  aka: 'CarlosAir',title:'Content Creation'},
        {first: 'David',         last: 'Thurlbeck',         aka: '',        title: 'Vehicle Creation'},
        {first: 'Janne',         last: 'Nummela',           aka: '',        title: 'Vehicle Creation'},
        {first: 'Jukka',         last: 'Muikkula',          aka: 'Miura',   title: 'Vehicle Creation'},
        {first: 'Karol',         last: 'Miklas',            aka: '',        title: 'Freelance 3D Vehicle Artist'},
        {first: 'Mardem',        last: 'Pires das Dores',   aka: '',        title: 'Vehicle Creation'},
        {first: 'Mikko',         last: 'Lesonen',           aka: '',        title: 'Vehicle Creation'},
        {first: 'Renju',         last: 'Therakathu',        aka: '',        title: 'Vehicle Creation'},
        {first: 'Sam',           last: 'Millington',        aka: 'DrowsySam',title:'Vehicle Creation / Support'},
        {first: 'Sebastian',     last: 'Wessel',            aka: '',        title: 'Vehicle Creation'},
        {first: 'Virtual Mechanix',last: '',                aka: '',        title: 'Vehicle Creation - Outsourcing Agency'},
        {first: 'Winston',       last: 'Broderick',         aka: '',        title: 'Vehicle Creation'},
        {first: 'Mitchell',      last: 'Sahl',              aka: 'B25Mitch',title: '3D Vehicle / Environment Artist'},
        {first: '',              last: '',                  aka: '',        title: ''},
        {first: 'Christin',      last: 'Walther',           aka: '',        title: 'Lead 3D Artist'},
        {first: 'Justin',        last: 'Roczniak',          aka: 'Donoteat',title: 'Environment Artist'},
        {first: 'Lisa',          last: 'Steinberg',         aka: '',        title: '2D Artist'},
        {first: 'Moses',         last: 'Mulinge',           aka: '',        title: '2D Artist'},
        {first: '',              last: '',                  aka: '',        title: ''},
        {first: 'Barend',        last: 'van der Meulen',    aka: '',        title: 'Content Creator'},
        {first: 'Matthias',      last: 'Niebergall',        aka: '',        title: 'Game Designer'},
        {first: 'SanityCheckMyGame',   last: '',            aka: '',        title: 'Additional Design'},
        {first: '',              last: '',                  aka: '',        title: ''},
        {first: 'Georgios',      last: 'Siantikos',         aka: 'gntikos', title: 'User Interface'},
        {first: 'Jonathan',      last: 'Randy',             aka: '',        title: 'Lead Developer'},
        {first: 'Mirco',         last: 'Weigel',            aka: 'theshark',title: 'User Interface'},
        {first: 'Svetlozar',     last: 'Valchev',           aka: '',        title: 'User Interface'},
        {first: 'Theodoros',     last: 'Manouilidis',       aka: '',        title: 'User Interface'},
        {first: 'Yale',          last: 'Hartmann',          aka: '',        title: 'User Interface'},
        {first: '',              last: '',                  aka: '',        title: ''},
        {first: 'Arend',         last: 'Stührmann',         aka: '',        title: 'Producer'},
        {first: 'Marie Cécile',  last: 'Jacq',              aka: '',        title: 'Producer'},
        {first: 'Nhung Van',     last: 'Ho',                aka: '',        title: 'Project Management'},
        {first: '',              last: '',                  aka: '',        title: ''},
        {first: 'Bhavinkumar Babulal',last: 'Arya',         aka: '',        title: 'Research Software Engineer'},
        {first: 'Carol',         last: 'Halim',             aka: 'Carotte', title: 'Research Software Engineer'},
        {first: 'Elmar',         last: 'Berghöfer',         aka: '',        title: 'Research'},
        {first: 'Mattia',        last: 'Vicari',            aka: '',        title: 'Research Software Engineer'},
        {first: '',              last: '',                  aka: '',        title: ''},
        {first: 'Camila',        last: 'Navia',             aka: '',        title: 'Operations Assistant'},
        {first: 'Danish',        last: 'Abbasi',            aka: '',        title: 'Business Development Intern'},
        {first: 'Lucien',        last: 'Frei',              aka: '',        title: 'Business Development Intern'},
        {first: 'Weiwei',        last: 'Kong',              aka: '',        title: 'Business Development Intern'},
        {first: 'Özgen',         last: 'Saatçilar',         aka: '',        title: 'Communications Consultant'},
        {first: 'Saskia',        last: 'Opitz',             aka: '',        title: 'Administration'},
        {first: '',              last: '',                  aka: '',        title: ''},
        {first: 'Hala',          last: 'Mahmoud',           aka: '',        title: 'Quality Assurance'},
        {first: 'Jan Niklas',    last: 'Hasse',             aka: '',        title: 'Quality Assurance'},
        {first: 'Kamil',         last: 'Kozak',             aka: '',        title: 'Quality Assurance'},
        {first: 'Kemisola',      last: 'Adeniyi',           aka: '',        title: 'Quality Assurance'},
        {first: 'Kaja',          last: 'Jambrek',           aka: '',        title: 'Quality Assurance'},
        {first: 'Rajinder',      last: 'Rajinder',          aka: '',        title: 'Quality Assurance'},
        {first: 'Safdar',        last: 'Mahmood',           aka: '',        title: 'Quality Assurance'},
        {first: 'Uros',          last: 'Sakic',             aka: 'Uki',     title: 'QA / Mod Support / Tools QA'},
        {first: '',              last: '',                  aka: '',        title: ''},
        {first: 'Konstantinos',  last: 'Stamou',            aka: '',        title: 'System Administrator'},
        {first: '',              last: '',                  aka: '',        title: ''},
        {first: 'Erik',          last: 'Heldt',             aka: '',        title: 'Documentation'},
        {first: 'Maxime',        last: 'Desharnais',        aka: '',        title: 'Documentation'},
        {first: 'Harm',          last: 'Schulz',            aka: '',        title: 'Student Assistant'},
        {first: 'Annisa',        last: 'Utami',             aka: '',        title: 'Student Assistant'},
        {first: 'Brandon',       last: 'Lynch',             aka: 'Chuck_Norris_',  title: 'Community Coordinator'},
        {first: 'Monica',        last: 'Huang',             aka: '',        title: 'Community Coordinator'},
    ]},
    { translateId: 'ui.credits.ourAwesomeCommunity', members: [
        {first: 'Daniel',   last: 'Jones',       aka: 'daniel_j'},
        {first: 'Dennis',   last: 'Wrekenhorst', aka: 'Dennis-W'},
        {first: 'Dustin',   last: 'Kutchara',    aka: 'dkutch'},
        {first: 'Kristian', last: 'Fagerland',   aka: ''},
        {first: 'Richard',  last: 'Sixsmith',    aka: 'Metalmuncher'},
        {first: 'Sergy',    last: 'Karpowicz',   aka: '0xsergy'},
        {first: 'Sven',     last: 'Nabeck',      aka: 'sputnik_1'},
        {first: 'Tom',      last: 'Verhoeve',    aka: 'Mythbuster'},
        {first: 'Yannis',   last: 'Vaiopoulos',  aka: 'JohnV'},
        {first: '',         last: '',            aka: 'Fufsgfen'}
    ]},
    { translateId: 'ui.credits.specialThanksTo', members: [
        {first: 'Luis',            last: 'Placid',       aka: '',              title: 'VFX Developer'},
        {first: 'Pierre-Michel',   last: 'Ricordel',     aka: 'pricorde'},
    ]},
    { translateId: 'ui.credits.soundtrack', members: [
        {first: 'Gabriel "gabester" Fink',    last: 'Copyright 2014', aka: 'Lonle'},
        {first: 'Mark "TDK" Knight',          last: 'Copyright 2018', aka: 'Element No. 10'},
        {first: 'Mark "TDK" Knight',          last: 'Copyright 2018', aka: 'Getting Away'},
        {first: 'Mark "TDK" Knight',          last: 'Copyright 2018', aka: 'Juno Rocks'},
        {first: 'Mark "TDK" Knight',          last: 'Copyright 2018', aka: 'Neon Night Racer'},
        {first: 'Mark "TDK" Knight',          last: 'Copyright 2018', aka: 'Night Driver'}
    ]},
    { translateId: 'ui.credits.madePossibleWith', members: [
        {first: 'FMOD Studio by Firelight Technologies Pty Ltd.', last: '',                aka: ''},
        {first: 'LuaJIT',                                         last: '',                aka: ''},
        {first: 'lua-intf, LuaBridge',                            last: '',                aka: ''},
        {first: 'Chromium Embedded Framework',                    last: '',                aka: ''},
        {first: 'AngularJS',                                      last: '',                aka: ''},
        {first: 'Vue.js',                                         last: '',                aka: ''},
        {first: 'Material Design',                                last: '',                aka: ''},
        {first: 'LuaSocket',                                      last: '',                aka: ''},
        {first: 'Dear ImGui',                                     last: '',                aka: ''},
        {first: 'Blender ®',                                      last: 'www.blender.org', aka: ''},
    ]},
    { translateId: '', members: [
        {first: '“DUALSHOCK” and “DualSense” are registered trademarks or trademarks of Sony Interactive Entertainment Inc. Library programs for DUALSHOCK®4 and DualSense™ wireless controllers © 2022 Sony Interactive Entertainment Inc.', last: '',                aka: ''},
    ]}
]